spring:
  kafka:
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    consumer:
#      key:
#        deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value:
#        deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    bootstrap-servers: rubik-hackathon.dev.intgdc.com:29092
    bootstrap-servers: localhost:9092
