## MySQL
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/icommerce'
    username: root
    password: password

  #'hibernate_sequence' doesn't exist
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      # TODO: drop and create table, good for testing, comment this in production
      ddl-auto: create
